### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Nojus297** [Nojus297/wedl#1]
@wrapper let's move it here. If you are interested, we could try to troubleshoot this.
If you can't share the link, maybe you could reproduce a link with similar properties without sensitive content?
And this one should work: https://we.tl/t-ZVlutYKnTR
It might have something to do with links created by _wetransfer_ plus user.
https://github.com/superalex/py-wetransfer/issues/29

**Comment by Nojus297** [comment]
Closing this as the person who reported the issue doesn't respond.

**Comment by nojus297** [comment]
@wrapper it should work now, I haven't realized before that email transfers behave differently.
