### ISSUE TITLE
Unable to find direct link

### ISSUE THREAD

**Issue by bamtan** [nojus297/wedl#2]
Hi, it seems to no longer be working 😢 

Have tried both urls: 

- `https://we.tl/t-xxxxxxxxxx` 
- `https://wetransfer.com/downloads/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxx` 

Both get the error `Unable to find direct link`

Tested on v0.1.1 with `wedl-linux-amd64` and `wedl-windows-amd64.exe`

**Comment by nojus297** [comment]
Hi.
Thanks for opening the issue.
It should be fixed now, let me know if it doesn't work.

**Comment by bamtan** [comment]
Thank you for the quick fix! Works perfectly again.
