### ISSUE TITLE
Unable to get transfer id

### ISSUE THREAD

**Issue by enten64** [nojus297/wedl#3]
Hi,

it (probably) stopped working. I'm getting an error: "Unable to get transfer id"

Tested on version 0.1.2, wedl-windows-amd64.exe

**Comment by nojus297** [comment]
Hi and thanks for reporting it.

It should be fixed now and an updated version available ﻿in the releases.

**Comment by enten64** [comment]
Hi,

thank you for your quick response. Unfortunately with version 0.1.3 i'm getting an error: "json: cannot unmarshal array into Go value of type map[string]interface".

**Comment by nojus297** [comment]
Wow, they was broke it again very quickly﻿.
Anyway, it should work now, try v0.1.4

**Comment by enten64** [comment]
Hi
V0.1.4 is working fine again. Thank you for your time.
