### ISSUE TITLE
How to know file name?

### ISSUE THREAD

**Issue by glukinho** [nojus297/wedl#5]
Hi, I want to use this program inside a script where I pipe wedl's stdout right to user's browser where the file is actually downloaded. Is there any way to know the name of the downloaded file?
Thank you!

I launch wedl this way: `/usr/local/sbin/wedl-linux-amd64 -o - https://wetransfer.com/downloads/lalalalalala/blablabla/lala`

**Comment by glukinho** [comment]
When I download the link using my regular browser, the file is downloaded with the name, for example, 'my-super-file.zip'. I want to know this name using wedl.

**Comment by glukinho** [comment]
I found out how to know file name by parsing HTML from Wetransfer link. Needed file name is contained in the tag `<meta property="og:title" content="my-super-file.zip">`

Here is how I get this information using PHP:

> $dom = new \DomDocument();
> $dom->strictErrorChecking = FALSE;
> @$dom->loadHTML($html);
>        
>  // get all meta og:... tags
> foreach ($dom->getElementsByTagName('meta') as $m){
>     $tag = $m->getAttribute('name') ?: $m->getAttribute('property');
>     if(in_array($tag,['description','keywords']) || strpos($tag,'og:')===0) $res[str_replace('og:','',$tag)] = utf8_decode($m->getAttribute('content'));
> }
> 
> $filename = $res['title'];

**Comment by nojus297** [comment]
Hi, if you use `wedl` without specifying output filename with `-o`, it creates the file with correct filename.
However, there is not much help from this if you don't want to write the file to disk, but pipe somewhere else.

I guess I could add an option that only writes filename to stdout and exits without downloading. Would that help you?

**Comment by glukinho** [comment]
Yes, it would help. I can't imagine another way to accomplish this using just one launch of wedl.

Also, it would be nice to be able to know file size to pass to user's browser. Now piped content size in unpredictable and a user can't imagine if he would wait 1 minute or 1 hour before download finishes.

I would offer you to implement something like `-i` key (from 'information') which provides all available information about the link in JSON format. For example: `wedl -i https://wetransfer.com/downloads/very/long/link`

output is something like: `{"file_name": "my-super-file.zip", "size": 854678, "author": "John Doe <john.doe@domain.com>", "mime_type": "application/zip", "download_link": "https://link-for-direct-download-using-any-http-client-like-curl-or-wget"}` (I don't know what info is available without downloading)

So, wedl should be launched twice: first to get file info, then to download the contents or pipe it somewhere. It would be very helpful in scripting. Thank you!

**Comment by nojus297** [comment]
The newest release should contain the relevant information. However, I found no way to find link author and wetransfer does not seem to tell the mimetype either, so these fields are left out.

**Comment by glukinho** [comment]
Thanks!
I mentioned author just for example. The most important is file name and size. Direct link is useful too.
